#!/usr/bin/env bash

echo "Que versão do PHP você deseja utilizar no container?"
echo "1 - PHP 7.1"
echo "2 - PHP 7.2"
echo "3 - PHP 7.3"

read opcao

if [ $opcao -lt 1 -o $opcao -gt 3 ];
then
  echo "Opção inválida"
  exit 1
else
  VERSAO_PHP="7.$opcao"
fi

if [ ! -d "src" ]; then
  git clone git@github.com:Bleez/magento-dev-pacotes.git src
else
  cp samples/magento.nginx.conf.sample src/nginx.conf.sample
fi

NOME_PASTA=${PWD##*/}

rm -f .env docker-compose.yml \
      docker-compose-$(uname -s).yml \
      docker-sync.yml \
      shell \
      root \
      image/bin/install-magento \
      config/nginx.conf \
      image/bin/redis-flush \
      image/extras/env.sample.php \

cp samples/docker-compose.sample.yml docker-compose.yml
cp samples/docker-compose-$(uname -s).sample.yml docker-compose-$(uname -s).yml
cp samples/docker-sync.sample.yml docker-sync.yml
cp samples/shell.sample shell
cp samples/root.sample root
cp samples/install-magento.sample image/bin/install-magento
cp samples/redis-flush.sample image/bin/redis-flush
cp samples/nginx.sample.conf config/nginx.conf
cp samples/env.sample.php image/extras/env.sample.php
cp samples/.env.sample .env

if [ ! -f "docker-compose.custom.yml" ]; then
  cp samples/docker-compose.custom.sample.yml docker-compose.custom.yml
fi

sed -i '' -e "s/<projeto>/$NOME_PASTA/g" \
          docker-compose.yml \
          docker-compose-$(uname -s).yml \
          docker-sync.yml \
          shell \
          root \
          image/bin/install-magento \
          image/bin/redis-flush \
          image/extras/env.sample.php \
          config/nginx.conf;

sed -i '' -e "s/<versao_php>/$VERSAO_PHP/g" \
          docker-compose.yml \
          docker-compose-$(uname -s).yml;

sed -i '' -e  "s#<path-local>#$PWD#g" .env;


sudo chmod u+x install kill logs shell start stop update root

echo "Concluído. Para iniciar execute: ./start"
